[[workers]]
    name = "Gatherer"
    initialCost = 10
    dailyCost = 5
    gathers = true # Optional gathers
    gathersType = "" # Optional gathers type
    gathersItemName = "" # Optional gathers item name. This will take priority over gathers type
    producesType = "basic" # Optional produces type
    producesItemName = "" # Optional produces item name. This will take priority over produces type
[[workers]]
    name = "Processor"
    initialCost = 20
    dailyCost = 10
    gathers = false
    buysType = "basic"
    producesType = "processed"
[[workers]]
    name = "Crafter"
    initialCost = 30
    dailyCost = 15
    gathers = false
    buysType = "processed"
    producesType = "luxury"
[[workers]]
    name = "Mechant"
    initialCost = 40
    dailyCost = 20
    gathers = false
    buysType = "luxury"
    producesType = "trade"
[[workers]]
    name = "Tax Collector"
    buys = true
    buysType = "trade"
    buyable = false